services:
  db:
    image: postgres:15
    container_name: postgres-db-orbis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-flask
    working_dir: /app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    networks:
      - backend-network
    restart: on-failure


volumes:
  postgres-data:
  pgadmin-data:

networks:
  backend-network:
    driver: bridge
